<?php
/* Smarty version 5.8.0, created on 2026-05-08 23:57:24
  from 'string:<p data-path-to-node="5"><b data-path-to-node="5" data-index-in-node="0">Effective Date: 9th May 2026</b></p>
<p data-path-to-node="6"><b data-path-to-node="6" data-index-in-node="0">PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING KIPTALK.</b></p>
<p data-path-to-node="7"><b data-path-to-node="7" data-index-in-node="0">1. ACCEPTANCE OF TERMS</b></p>
<p data-path-to-node="8">This Terms and Conditions agreement (&ldquo;Terms&rdquo;, &ldquo;Agreement&rdquo;) is a legally binding contract between you (&ldquo;User&rdquo;, &ldquo;you&rdquo;, or &ldquo;your&rdquo;) and [KipTalk Inc./KipTalk Communications Ltd] (&ldquo;KipTalk&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;), governing your access to and use of the KipTalk mobile application, website, and associated services (collectively, the &ldquo;Service&rdquo;).</p>
<p data-path-to-node="9">By downloading, installing, accessing, or using the Service, you represent that you: a) Are at least [e.g., 13/16/18] years of age (or the minimum legal age required in your jurisdiction to form a binding contract) and have the legal capacity to enter into this Agreement. b) Have read, understood, and agree to be bound by these Terms. c) If you are using the Service on behalf of an entity, organization, or company, you represent and warrant that you have the authority to bind that entity to these Terms.</p>
<p data-path-to-node="10">If you do not agree with any part of these Terms, you must immediately stop using the Service and delete the KipTalk application from your device(s).</p>
<p data-path-to-node="11"><b data-path-to-node="11" data-index-in-node="0">2. MODIFICATIONS TO TERMS</b></p>
<p data-path-to-node="12">KipTalk reserves the right, at its sole discretion, to modify, amend, or replace these Terms at any time. We will notify you of any material changes by [e.g., posting the updated Terms within the Service, sending an in-app notification, or via email]. The "Effective Date" at the top will indicate when the last revisions occurred.</p>
<p data-path-to-node="13">Your continued use of the Service after any such changes constitute your acceptance of the revised Terms. It is your responsibility to review the Terms periodically.</p>
<p data-path-to-node="14"><b data-path-to-node="14" data-index-in-node="0">3. PRIVACY AND DATA PROTECTION</b></p>
<p data-path-to-node="15">Your privacy is paramount to us. Our data practices, including how we collect, use, and share information about you, are detailed in our <b data-path-to-node="15" data-index-in-node="137">Privacy Policy</b>, which is incorporated into these Terms by reference. Please review the Privacy Policy carefully. By using the Service, you consent to the collection and use of your data as outlined in that policy.</p>
<p data-path-to-node="16"><b data-path-to-node="16" data-index-in-node="0">4. ELIGIBILITY AND ACCOUNT REGISTRATION</b></p>
<p data-path-to-node="17">To access certain features of the Service, you may be required to register for an account. When you create an account, you agree to: a) Provide accurate, current, and complete information. b) Maintain the security of your password and accept all risks of unauthorized access to your account. c) Promptly update your account information if any details change. d) Not share your account credentials or permit anyone else to use your account. e) Be solely responsible for all activity that occurs under your account.</p>
<p data-path-to-node="18">KipTalk reserves the right to refuse registration or cancel an account at its discretion.</p>
<p data-path-to-node="19"><b data-path-to-node="19" data-index-in-node="0">5. DESCRIPTION OF SERVICE</b></p>
<p data-path-to-node="20">KipTalk is a communication platform offering features such as [list core features, e.g., instant messaging, voice calls, video calls, media sharing, group chats, etc.]. The availability and performance of these features may depend on your device, network, and location.</p>
<p data-path-to-node="21">KipTalk reserves the right to modify, suspend, or discontinue the Service, or any part thereof, at any time, with or without notice.</p>
<p data-path-to-node="22"><b data-path-to-node="22" data-index-in-node="0">6. USER CONDUCT AND PROHIBITED USES</b></p>
<p data-path-to-node="23">You are solely responsible for your conduct and any content that you transmit, share, or upload using the Service (&ldquo;User Content&rdquo;). You agree not to use the Service to:</p>
<p data-path-to-node="24">a) <b data-path-to-node="24" data-index-in-node="3">Violate Laws:</b> Engage in any activity that is illegal or promotes illegal activities. b) <b data-path-to-node="24" data-index-in-node="91">Harm or Exploit Minors:</b> Transmit, store, or share content that harms, exploits, or endangers minors in any way. c) <b data-path-to-node="24" data-index-in-node="206">Infringe Rights:</b> Post or share content that infringes upon the intellectual property, privacy, publicity, or other rights of any third party. d) <b data-path-to-node="24" data-index-in-node="351">Transmit Harmful Content:</b> Upload, post, or transmit content that is obscene, hateful, discriminatory, harassing, threatening, defamatory, or otherwise offensive. e) <b data-path-to-node="24" data-index-in-node="516">Engage in Harassment:</b> Harass, abuse, or stalk other users. f) <b data-path-to-node="24" data-index-in-node="578">Distribute Malware:</b> Distribute viruses, spyware, or other harmful computer code. g) <b data-path-to-node="24" data-index-in-node="662">Interfere with Service:</b> Attempt to interfere with, disrupt, or negatively affect the Service or servers. h) <b data-path-to-node="24" data-index-in-node="770">Use Automation:</b> Use automated means (e.g., bots, scripts) to access the Service or collect information without authorization. i) <b data-path-to-node="24" data-index-in-node="899">Violate Privacy:</b> Collect personal data about other users without their consent. j) <b data-path-to-node="24" data-index-in-node="982">Spam:</b> Send unsolicited messages, advertisements, or promotional materials (spam). k) <b data-path-to-node="24" data-index-in-node="1067">Misrepresent Identity:</b> Impersonate any person or entity or misrepresent your affiliation.</p>
<p data-path-to-node="25">KipTalk reserves the right (but assumes no obligation) to monitor User Content and may remove content or suspend/terminate accounts that violate this Agreement.</p>
<p data-path-to-node="26"><b data-path-to-node="26" data-index-in-node="0">7. USER CONTENT AND INTELLECTUAL PROPERTY</b></p>
<p data-path-to-node="27">a) <b data-path-to-node="27" data-index-in-node="3">Your Ownership:</b> You retain all ownership rights to the User Content you create or share through the Service. b) <b data-path-to-node="27" data-index-in-node="115">License to KipTalk:</b> By submitting, posting, or displaying User Content, you grant KipTalk a worldwide, non-exclusive, royalty-free, fully paid-up license to use, reproduce, modify, adapt, publish, translate, and distribute such User Content [add limitations here based on service type, e.g., solely for the purpose of operating, protecting, and improving the Service]. c) <b data-path-to-node="27" data-index-in-node="487">KipTalk&rsquo;s Property:</b> All rights, title, and interest in and to the Service (including the KipTalk name, logo, software, and overall design) are and will remain the exclusive property of KipTalk and its licensors. The "KipTalk" trademark and logo are protected. You may not use KipTalk's trademarks or copyrighted material without prior written permission.</p>
<p data-path-to-node="28"><b data-path-to-node="28" data-index-in-node="0">8. FEES, PAYMENTS, AND SUBSCRIPTIONS (If Applicable)</b></p>
<p data-path-to-node="29">Certain features of KipTalk may require payment (e.g., premium subscriptions, specific in-app purchases).</p>
<p data-path-to-node="30">a) <b data-path-to-node="30" data-index-in-node="3">Pricing:</b> All prices are as listed within the Service and are subject to change. b) <b data-path-to-node="30" data-index-in-node="86">Payments:</b> Payments are processed through [mention the app store platforms, e.g., Apple App Store or Google Play Store, or a specific third-party processor]. You agree to their terms and conditions regarding payments. c) <b data-path-to-node="30" data-index-in-node="306">Taxes:</b> Prices generally exclude applicable taxes unless stated otherwise. d) <b data-path-to-node="30" data-index-in-node="383">Subscriptions:</b> If you purchase a subscription, it will automatically renew at the end of the subscription period unless canceled at least 24 hours before the renewal date. You can manage and cancel subscriptions through your app store settings. e) <b data-path-to-node="30" data-index-in-node="631">Refunds:</b> All purchases are final, and refunds are subject to the policies of the relevant app store [Apple App Store Refund Policy / Google Play Refund Policy] or the specific third-party processor. KipTalk generally does not provide refunds.</p>
<p data-path-to-node="31"><b data-path-to-node="31" data-index-in-node="0">9. THIRD-PARTY SERVICES AND LINKS</b></p>
<p data-path-to-node="32">The Service may contain links to third-party websites, applications, or services that are not owned or controlled by KipTalk. KipTalk has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party services. By using the Service, you acknowledge and agree that KipTalk is not responsible for the availability of such external sites or resources.</p>
<p data-path-to-node="33"><b data-path-to-node="33" data-index-in-node="0">10. DISCLAIMER OF WARRANTIES</b></p>
<p data-path-to-node="34">THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, KIPTALK EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
<p data-path-to-node="35">KIPTALK DOES NOT WARRANT THAT (I) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (II) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE; (III) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS.</p>
<p data-path-to-node="36"><b data-path-to-node="36" data-index-in-node="0">11. LIMITATION OF LIABILITY</b></p>
<p data-path-to-node="37">TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, KIPTALK AND ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, AND LICENSORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING, WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:</p>
<p data-path-to-node="38">(I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (II) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; (III) ANY CONTENT OBTAINED FROM THE SERVICE; AND (IV) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, WHETHER OR NOT KIPTALK HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.</p>
<p data-path-to-node="39">IN NO EVENT SHALL KIPTALK&rsquo;S TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING THE SERVICE DURING THE [e.g., TWELVE (12)] MONTHS IMMEDIATELY PRECEDING THE CLAIM.</p>
<p data-path-to-node="40"><b data-path-to-node="40" data-index-in-node="0">12. INDEMNIFICATION</b></p>
<p data-path-to-node="41">You agree to indemnify, defend, and hold harmless KipTalk and its affiliates, officers, employees, agents, and licensors from and against any and all claims, demands, damages, costs, liabilities, and expenses (including reasonable attorneys' fees) arising out of or in connection with: a) Your use of the Service. b) Your violation of these Terms. c) Your User Content. d) Your violation of any rights of another party, including intellectual property rights.</p>
<p data-path-to-node="42"><b data-path-to-node="42" data-index-in-node="0">13. TERMINATION</b></p>
<p data-path-to-node="43">We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason whatsoever, including, without limitation, if you breach these Terms.</p>
<p data-path-to-node="44">Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service. All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.</p>
<p data-path-to-node="45"><b data-path-to-node="45" data-index-in-node="0">14. GOVERNING LAW AND JURISDICTION</b></p>
<p data-path-to-node="46">These Terms shall be governed by and construed in accordance with the laws of [State/Country, e.g., the State of Delaware], without regard to its conflict of law provisions. Any legal suit, action, or proceeding arising out of or related to these Terms or the Service shall be instituted exclusively in the federal or state courts located in [City, State].</p>
<p data-path-to-node="47"><b data-path-to-node="47" data-index-in-node="0">15. DISPUTE RESOLUTION AND ARBITRATION (Highly Recommended Clause)</b></p>
<p data-path-to-node="48"><b data-path-to-node="48" data-index-in-node="0">PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT.</b></p>
<p data-path-to-node="49">Most concerns can be resolved quickly by contacting our support team at [e.g., support@kiptalk.com]. If we cannot resolve a dispute, you and KipTalk agree to resolve any claim arising out of or relating to these Terms or the Service through final and binding arbitration, rather than in court [except for small claims matters as specified below].</p>
<p data-path-to-node="50">a) <b data-path-to-node="50" data-index-in-node="3">Binding Arbitration:</b> You agree that any dispute will be administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules and, where appropriate, the AAA&rsquo;s Supplementary Procedures for Consumer-Related Disputes. The arbitration will take place in [City, State], or your hometown if required by AAA rules. b) <b data-path-to-node="50" data-index-in-node="343">Class Action Waiver:</b> YOU AGREE THAT EACH PARTY MAY ONLY BRING CLAIMS AGAINST THE OTHER IN AN INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. c) <b data-path-to-node="50" data-index-in-node="551">Exceptions:</b> Notwithstanding the above, either party may bring an individual action in a small claims court. Also, either party may seek injunctive relief from a court to protect its intellectual property rights.</p>
<p data-path-to-node="51"><b data-path-to-node="51" data-index-in-node="0">16. ENTIRE AGREEMENT</b></p>
<p data-path-to-node="52">These Terms, together with the Privacy Policy and any other legal notices published by KipTalk, constitute the entire agreement between you and KipTalk regarding the Service and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral.</p>
<p data-path-to-node="53"><b data-path-to-node="53" data-index-in-node="0">17. WAIVER AND SEVERABILITY</b></p>
<p data-path-to-node="54">No waiver by KipTalk of any term or condition set out in these Terms shall be deemed a further or continuing waiver of such term or condition, and any failure of KipTalk to assert a right or provision under these Terms shall not constitute a waiver of such right or provision. If any provision of these Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent necessary so that the remaining provisions of the Terms will continue in full force and effect.</p>
<p data-path-to-node="55"><b data-path-to-node="55" data-index-in-node="0">18. CONTACT US</b></p>
<p data-path-to-node="56">If you have any questions or feedback regarding these Terms, please contact us at:</p>
<p data-path-to-node="57"><b data-path-to-node="57" data-index-in-node="0">[KipTalk Inc./Company Name]</b> [Mailing Address] <b data-path-to-node="57" data-index-in-node="46">Email:</b> [legal@kiptalk.com / info@kiptalk.com]</p>' */

/* @var \Smarty\Template $_smarty_tpl */
if ($_smarty_tpl->getCompiled()->isFresh($_smarty_tpl, array (
  'version' => '5.8.0',
  'unifunc' => 'content_69fe7864d134e2_05057760',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
  ),
  'includes' => 
  array (
  ),
))) {
function content_69fe7864d134e2_05057760 (\Smarty\Template $_smarty_tpl) {
$_smarty_current_dir = '.';
?><p data-path-to-node="5"><b data-path-to-node="5" data-index-in-node="0">Effective Date: 9th May 2026</b></p>
<p data-path-to-node="6"><b data-path-to-node="6" data-index-in-node="0">PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING KIPTALK.</b></p>
<p data-path-to-node="7"><b data-path-to-node="7" data-index-in-node="0">1. ACCEPTANCE OF TERMS</b></p>
<p data-path-to-node="8">This Terms and Conditions agreement (&ldquo;Terms&rdquo;, &ldquo;Agreement&rdquo;) is a legally binding contract between you (&ldquo;User&rdquo;, &ldquo;you&rdquo;, or &ldquo;your&rdquo;) and [KipTalk Inc./KipTalk Communications Ltd] (&ldquo;KipTalk&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;), governing your access to and use of the KipTalk mobile application, website, and associated services (collectively, the &ldquo;Service&rdquo;).</p>
<p data-path-to-node="9">By downloading, installing, accessing, or using the Service, you represent that you: a) Are at least [e.g., 13/16/18] years of age (or the minimum legal age required in your jurisdiction to form a binding contract) and have the legal capacity to enter into this Agreement. b) Have read, understood, and agree to be bound by these Terms. c) If you are using the Service on behalf of an entity, organization, or company, you represent and warrant that you have the authority to bind that entity to these Terms.</p>
<p data-path-to-node="10">If you do not agree with any part of these Terms, you must immediately stop using the Service and delete the KipTalk application from your device(s).</p>
<p data-path-to-node="11"><b data-path-to-node="11" data-index-in-node="0">2. MODIFICATIONS TO TERMS</b></p>
<p data-path-to-node="12">KipTalk reserves the right, at its sole discretion, to modify, amend, or replace these Terms at any time. We will notify you of any material changes by [e.g., posting the updated Terms within the Service, sending an in-app notification, or via email]. The "Effective Date" at the top will indicate when the last revisions occurred.</p>
<p data-path-to-node="13">Your continued use of the Service after any such changes constitute your acceptance of the revised Terms. It is your responsibility to review the Terms periodically.</p>
<p data-path-to-node="14"><b data-path-to-node="14" data-index-in-node="0">3. PRIVACY AND DATA PROTECTION</b></p>
<p data-path-to-node="15">Your privacy is paramount to us. Our data practices, including how we collect, use, and share information about you, are detailed in our <b data-path-to-node="15" data-index-in-node="137">Privacy Policy</b>, which is incorporated into these Terms by reference. Please review the Privacy Policy carefully. By using the Service, you consent to the collection and use of your data as outlined in that policy.</p>
<p data-path-to-node="16"><b data-path-to-node="16" data-index-in-node="0">4. ELIGIBILITY AND ACCOUNT REGISTRATION</b></p>
<p data-path-to-node="17">To access certain features of the Service, you may be required to register for an account. When you create an account, you agree to: a) Provide accurate, current, and complete information. b) Maintain the security of your password and accept all risks of unauthorized access to your account. c) Promptly update your account information if any details change. d) Not share your account credentials or permit anyone else to use your account. e) Be solely responsible for all activity that occurs under your account.</p>
<p data-path-to-node="18">KipTalk reserves the right to refuse registration or cancel an account at its discretion.</p>
<p data-path-to-node="19"><b data-path-to-node="19" data-index-in-node="0">5. DESCRIPTION OF SERVICE</b></p>
<p data-path-to-node="20">KipTalk is a communication platform offering features such as [list core features, e.g., instant messaging, voice calls, video calls, media sharing, group chats, etc.]. The availability and performance of these features may depend on your device, network, and location.</p>
<p data-path-to-node="21">KipTalk reserves the right to modify, suspend, or discontinue the Service, or any part thereof, at any time, with or without notice.</p>
<p data-path-to-node="22"><b data-path-to-node="22" data-index-in-node="0">6. USER CONDUCT AND PROHIBITED USES</b></p>
<p data-path-to-node="23">You are solely responsible for your conduct and any content that you transmit, share, or upload using the Service (&ldquo;User Content&rdquo;). You agree not to use the Service to:</p>
<p data-path-to-node="24">a) <b data-path-to-node="24" data-index-in-node="3">Violate Laws:</b> Engage in any activity that is illegal or promotes illegal activities. b) <b data-path-to-node="24" data-index-in-node="91">Harm or Exploit Minors:</b> Transmit, store, or share content that harms, exploits, or endangers minors in any way. c) <b data-path-to-node="24" data-index-in-node="206">Infringe Rights:</b> Post or share content that infringes upon the intellectual property, privacy, publicity, or other rights of any third party. d) <b data-path-to-node="24" data-index-in-node="351">Transmit Harmful Content:</b> Upload, post, or transmit content that is obscene, hateful, discriminatory, harassing, threatening, defamatory, or otherwise offensive. e) <b data-path-to-node="24" data-index-in-node="516">Engage in Harassment:</b> Harass, abuse, or stalk other users. f) <b data-path-to-node="24" data-index-in-node="578">Distribute Malware:</b> Distribute viruses, spyware, or other harmful computer code. g) <b data-path-to-node="24" data-index-in-node="662">Interfere with Service:</b> Attempt to interfere with, disrupt, or negatively affect the Service or servers. h) <b data-path-to-node="24" data-index-in-node="770">Use Automation:</b> Use automated means (e.g., bots, scripts) to access the Service or collect information without authorization. i) <b data-path-to-node="24" data-index-in-node="899">Violate Privacy:</b> Collect personal data about other users without their consent. j) <b data-path-to-node="24" data-index-in-node="982">Spam:</b> Send unsolicited messages, advertisements, or promotional materials (spam). k) <b data-path-to-node="24" data-index-in-node="1067">Misrepresent Identity:</b> Impersonate any person or entity or misrepresent your affiliation.</p>
<p data-path-to-node="25">KipTalk reserves the right (but assumes no obligation) to monitor User Content and may remove content or suspend/terminate accounts that violate this Agreement.</p>
<p data-path-to-node="26"><b data-path-to-node="26" data-index-in-node="0">7. USER CONTENT AND INTELLECTUAL PROPERTY</b></p>
<p data-path-to-node="27">a) <b data-path-to-node="27" data-index-in-node="3">Your Ownership:</b> You retain all ownership rights to the User Content you create or share through the Service. b) <b data-path-to-node="27" data-index-in-node="115">License to KipTalk:</b> By submitting, posting, or displaying User Content, you grant KipTalk a worldwide, non-exclusive, royalty-free, fully paid-up license to use, reproduce, modify, adapt, publish, translate, and distribute such User Content [add limitations here based on service type, e.g., solely for the purpose of operating, protecting, and improving the Service]. c) <b data-path-to-node="27" data-index-in-node="487">KipTalk&rsquo;s Property:</b> All rights, title, and interest in and to the Service (including the KipTalk name, logo, software, and overall design) are and will remain the exclusive property of KipTalk and its licensors. The "KipTalk" trademark and logo are protected. You may not use KipTalk's trademarks or copyrighted material without prior written permission.</p>
<p data-path-to-node="28"><b data-path-to-node="28" data-index-in-node="0">8. FEES, PAYMENTS, AND SUBSCRIPTIONS (If Applicable)</b></p>
<p data-path-to-node="29">Certain features of KipTalk may require payment (e.g., premium subscriptions, specific in-app purchases).</p>
<p data-path-to-node="30">a) <b data-path-to-node="30" data-index-in-node="3">Pricing:</b> All prices are as listed within the Service and are subject to change. b) <b data-path-to-node="30" data-index-in-node="86">Payments:</b> Payments are processed through [mention the app store platforms, e.g., Apple App Store or Google Play Store, or a specific third-party processor]. You agree to their terms and conditions regarding payments. c) <b data-path-to-node="30" data-index-in-node="306">Taxes:</b> Prices generally exclude applicable taxes unless stated otherwise. d) <b data-path-to-node="30" data-index-in-node="383">Subscriptions:</b> If you purchase a subscription, it will automatically renew at the end of the subscription period unless canceled at least 24 hours before the renewal date. You can manage and cancel subscriptions through your app store settings. e) <b data-path-to-node="30" data-index-in-node="631">Refunds:</b> All purchases are final, and refunds are subject to the policies of the relevant app store [Apple App Store Refund Policy / Google Play Refund Policy] or the specific third-party processor. KipTalk generally does not provide refunds.</p>
<p data-path-to-node="31"><b data-path-to-node="31" data-index-in-node="0">9. THIRD-PARTY SERVICES AND LINKS</b></p>
<p data-path-to-node="32">The Service may contain links to third-party websites, applications, or services that are not owned or controlled by KipTalk. KipTalk has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party services. By using the Service, you acknowledge and agree that KipTalk is not responsible for the availability of such external sites or resources.</p>
<p data-path-to-node="33"><b data-path-to-node="33" data-index-in-node="0">10. DISCLAIMER OF WARRANTIES</b></p>
<p data-path-to-node="34">THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, KIPTALK EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
<p data-path-to-node="35">KIPTALK DOES NOT WARRANT THAT (I) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (II) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE; (III) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS.</p>
<p data-path-to-node="36"><b data-path-to-node="36" data-index-in-node="0">11. LIMITATION OF LIABILITY</b></p>
<p data-path-to-node="37">TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, KIPTALK AND ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, AND LICENSORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING, WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:</p>
<p data-path-to-node="38">(I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (II) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; (III) ANY CONTENT OBTAINED FROM THE SERVICE; AND (IV) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, WHETHER OR NOT KIPTALK HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.</p>
<p data-path-to-node="39">IN NO EVENT SHALL KIPTALK&rsquo;S TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING THE SERVICE DURING THE [e.g., TWELVE (12)] MONTHS IMMEDIATELY PRECEDING THE CLAIM.</p>
<p data-path-to-node="40"><b data-path-to-node="40" data-index-in-node="0">12. INDEMNIFICATION</b></p>
<p data-path-to-node="41">You agree to indemnify, defend, and hold harmless KipTalk and its affiliates, officers, employees, agents, and licensors from and against any and all claims, demands, damages, costs, liabilities, and expenses (including reasonable attorneys' fees) arising out of or in connection with: a) Your use of the Service. b) Your violation of these Terms. c) Your User Content. d) Your violation of any rights of another party, including intellectual property rights.</p>
<p data-path-to-node="42"><b data-path-to-node="42" data-index-in-node="0">13. TERMINATION</b></p>
<p data-path-to-node="43">We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason whatsoever, including, without limitation, if you breach these Terms.</p>
<p data-path-to-node="44">Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service. All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.</p>
<p data-path-to-node="45"><b data-path-to-node="45" data-index-in-node="0">14. GOVERNING LAW AND JURISDICTION</b></p>
<p data-path-to-node="46">These Terms shall be governed by and construed in accordance with the laws of [State/Country, e.g., the State of Delaware], without regard to its conflict of law provisions. Any legal suit, action, or proceeding arising out of or related to these Terms or the Service shall be instituted exclusively in the federal or state courts located in [City, State].</p>
<p data-path-to-node="47"><b data-path-to-node="47" data-index-in-node="0">15. DISPUTE RESOLUTION AND ARBITRATION (Highly Recommended Clause)</b></p>
<p data-path-to-node="48"><b data-path-to-node="48" data-index-in-node="0">PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT.</b></p>
<p data-path-to-node="49">Most concerns can be resolved quickly by contacting our support team at [e.g., support@kiptalk.com]. If we cannot resolve a dispute, you and KipTalk agree to resolve any claim arising out of or relating to these Terms or the Service through final and binding arbitration, rather than in court [except for small claims matters as specified below].</p>
<p data-path-to-node="50">a) <b data-path-to-node="50" data-index-in-node="3">Binding Arbitration:</b> You agree that any dispute will be administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules and, where appropriate, the AAA&rsquo;s Supplementary Procedures for Consumer-Related Disputes. The arbitration will take place in [City, State], or your hometown if required by AAA rules. b) <b data-path-to-node="50" data-index-in-node="343">Class Action Waiver:</b> YOU AGREE THAT EACH PARTY MAY ONLY BRING CLAIMS AGAINST THE OTHER IN AN INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. c) <b data-path-to-node="50" data-index-in-node="551">Exceptions:</b> Notwithstanding the above, either party may bring an individual action in a small claims court. Also, either party may seek injunctive relief from a court to protect its intellectual property rights.</p>
<p data-path-to-node="51"><b data-path-to-node="51" data-index-in-node="0">16. ENTIRE AGREEMENT</b></p>
<p data-path-to-node="52">These Terms, together with the Privacy Policy and any other legal notices published by KipTalk, constitute the entire agreement between you and KipTalk regarding the Service and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral.</p>
<p data-path-to-node="53"><b data-path-to-node="53" data-index-in-node="0">17. WAIVER AND SEVERABILITY</b></p>
<p data-path-to-node="54">No waiver by KipTalk of any term or condition set out in these Terms shall be deemed a further or continuing waiver of such term or condition, and any failure of KipTalk to assert a right or provision under these Terms shall not constitute a waiver of such right or provision. If any provision of these Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent necessary so that the remaining provisions of the Terms will continue in full force and effect.</p>
<p data-path-to-node="55"><b data-path-to-node="55" data-index-in-node="0">18. CONTACT US</b></p>
<p data-path-to-node="56">If you have any questions or feedback regarding these Terms, please contact us at:</p>
<p data-path-to-node="57"><b data-path-to-node="57" data-index-in-node="0">[KipTalk Inc./Company Name]</b> [Mailing Address] <b data-path-to-node="57" data-index-in-node="46">Email:</b> [legal@kiptalk.com / info@kiptalk.com]</p><?php }
}
